[package]
name = "pea-wallet"
version = "0.6.2"
edition = "2021"
license = "MIT"
description = "エンドウ"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-core = { version = "0.6", path = "../core" }
pea-address = { version = "0.6", path = "../address" }
pea-int = { version = "0.4", path = "../int" }
pea-api = { version = "0.6", path = "../api" }
pea-key = { version = "0.6", path = "../key" }
pea-stake = { version = "0.7", path = "../stake" }
pea-transaction = { version = "0.8", path = "../transaction" }
chacha20poly1305 = "0.10"
inquire = "0.3"
colored = "2.0"
argon2 = "0.4"
zxcvbn = "2.2"
chrono = "0.4"
hex = "0.4"
crossterm = "0.25"
log = "0.4"
tokio = { version = "1.24", features = ["full"] }
clap = { version = "3.2", features = ["derive"] }
rand = "0.8"