[package]
name = "pea-db"
version = "0.7.2"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-int = { version = "0.4", path = "../int" }
pea-block = { version = "0.6", path = "../block" }
pea-core = { version = "0.6", path = "../core" }
pea-stake = { version = "0.7", path = "../stake" }
pea-transaction = { version = "0.8", path = "../transaction" }
pea-tree = { version = "0.4", path = "../tree" }
rocksdb = "0.19"
bincode = "1.3"
tempdir = "0.3"